title: Stackbit Fresh Theme (TEST)
baseURL: /
params:
  footer:
    content: '&copy; All rights reserved.'
    links:
      - new_window: true
        text: Made with Stackbit
        url: 'https://www.stackbit.com'
  header:
    bg: dark
    has_nav: true
    has_social: true
    profile_img: images/avatar.png
    tagline: Header Tagline
    title: Stackbit Fresh
  layout_style: overflow
  palette: blue
disableKinds:
  - RSS
